/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/logo.png)
  final logo = r'assets/images/logo.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_1.png)
  final onboarding_1 = r'assets/images/onboarding/onboarding_1.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_3.png)
  final onboarding_3 = r'assets/images/onboarding/onboarding_3.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_2.png)
  final onboarding_2 = r'assets/images/onboarding/onboarding_2.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_bg.png)
  final onboarding_bg = r'assets/images/onboarding/onboarding_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/heart.svg)
  final heart = r'assets/images/onboarding/heart.svg';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/lines_bg.png)
  final lines_bg = r'assets/images/profile/lines_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/welcome_image.png)
  final welcome_image = r'assets/images/profile/welcome_image.png';
}

class _SvgResources {
  const _SvgResources();
}
