/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/launcher.png)
  final launcher = r'assets/images/launcher.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/video_chat_bg.png)
  final video_chat_bg = r'assets/images/video_chat_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/senpai_logo.png)
  final senpai_logo = r'assets/images/senpai_logo.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/logo.png)
  final logo = r'assets/images/logo.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile.png)
  final profile = r'assets/images/profile.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/card_bg.png)
  final card_bg = r'assets/images/card_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/onboarding/onboarding_1.png)
  final onboarding_1 = r'assets/images/onboarding/onboarding_1.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/onboarding/onboarding_3.png)
  final onboarding_3 = r'assets/images/onboarding/onboarding_3.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/onboarding/onboarding_2.png)
  final onboarding_2 = r'assets/images/onboarding/onboarding_2.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/onboarding/onboarding_bg.png)
  final onboarding_bg = r'assets/images/onboarding/onboarding_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/onboarding/heart.svg)
  final heart = r'assets/images/onboarding/heart.svg';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/start_match_bg.png)
  final start_match_bg = r'assets/images/profile/start_match_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/spotify_logo_image.png)
  final spotify_logo_image = r'assets/images/profile/spotify_logo_image.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/btn_discord.png)
  final btn_discord = r'assets/images/profile/btn_discord.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/btn_twitter.png)
  final btn_twitter = r'assets/images/profile/btn_twitter.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/photo_not_verified.png)
  final photo_not_verified = r'assets/images/profile/photo_not_verified.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/spotify_image.png)
  final spotify_image = r'assets/images/profile/spotify_image.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/settings_avatar_header_bg.png)
  final settings_avatar_header_bg = r'assets/images/profile/settings_avatar_header_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/location_bg.png)
  final location_bg = r'assets/images/profile/location_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/btn_reddit.png)
  final btn_reddit = r'assets/images/profile/btn_reddit.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/welcome_image.png)
  final welcome_image = r'assets/images/profile/welcome_image.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/verify_user_photo.png)
  final verify_user_photo = r'assets/images/profile/verify_user_photo.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/premium_image.png)
  final premium_image = r'assets/images/profile/premium_image.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/lines_bg.png)
  final lines_bg = r'assets/images/profile/lines_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/marker_icon.png)
  final marker_icon = r'assets/images/profile/marker_icon.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/anime_empty.png)
  final anime_empty = r'assets/images/profile/anime_empty.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/anime_header.png)
  final anime_header = r'assets/images/profile/anime_header.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/photo_verified.png)
  final photo_verified = r'assets/images/profile/photo_verified.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/profile/spotify_bg.png)
  final spotify_bg = r'assets/images/profile/spotify_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/accept_btn_bg.png)
  final accept_btn_bg = r'assets/images/match/accept_btn_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/lobby_bg.png)
  final lobby_bg = r'assets/images/match/lobby_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/super_like_bg.png)
  final super_like_bg = r'assets/images/match/super_like_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/profile_verify_bg.png)
  final profile_verify_bg = r'assets/images/match/profile_verify_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/dark_bg.png)
  final dark_bg = r'assets/images/match/dark_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/people_bg.png)
  final people_bg = r'assets/images/match/people_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/invite_accept_bg.png)
  final invite_accept_bg = r'assets/images/match/invite_accept_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/invite_black_bg.png)
  final invite_black_bg = r'assets/images/match/invite_black_bg.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/match_successful.png)
  final match_successful = r'assets/images/match/match_successful.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/match/profile_verify_shadow.png)
  final profile_verify_shadow = r'assets/images/match/profile_verify_shadow.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/avatar_shop/new_tag.png)
  final new_tag = r'assets/images/avatar_shop/new_tag.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/avatar_shop/premium_frame.png)
  final premium_frame = r'assets/images/avatar_shop/premium_frame.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/avatar_shop/avatar_shop_item_overlay.png)
  final avatar_shop_item_overlay = r'assets/images/avatar_shop/avatar_shop_item_overlay.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/chat/empty_conversation_search.png)
  final empty_conversation_search = r'assets/images/chat/empty_conversation_search.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/chat/empty_animations.png)
  final empty_animations = r'assets/images/chat/empty_animations.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/chat/giphy_attribution.png)
  final giphy_attribution = r'assets/images/chat/giphy_attribution.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/chat/empty_conversations.png)
  final empty_conversations = r'assets/images/chat/empty_conversations.png';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/events/event_image_icon.svg)
  final event_image_icon = r'assets/images/events/event_image_icon.svg';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/events/event_button_icon.svg)
  final event_button_icon = r'assets/images/events/event_button_icon.svg';

  /// ![](/Users/herbertjoseph/Desktop/Projects/senpai-app/assets/images/events/empty_events_list.png)
  final empty_events_list = r'assets/images/events/empty_events_list.png';
}

class _SvgResources {
  const _SvgResources();
}
