/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/launcher.png)
  final launcher = r'assets/images/launcher.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/logo.png)
  final logo = r'assets/images/logo.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_1.png)
  final onboarding_1 = r'assets/images/onboarding/onboarding_1.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_3.png)
  final onboarding_3 = r'assets/images/onboarding/onboarding_3.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_2.png)
  final onboarding_2 = r'assets/images/onboarding/onboarding_2.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/onboarding_bg.png)
  final onboarding_bg = r'assets/images/onboarding/onboarding_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/onboarding/heart.svg)
  final heart = r'assets/images/onboarding/heart.svg';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/start_match_bg.png)
  final start_match_bg = r'assets/images/profile/start_match_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/photo_not_verified.png)
  final photo_not_verified = r'assets/images/profile/photo_not_verified.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/photo_verifed.png)
  final photo_verifed = r'assets/images/profile/photo_verifed.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/location_bg.png)
  final location_bg = r'assets/images/profile/location_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/welcome_image.png)
  final welcome_image = r'assets/images/profile/welcome_image.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/verify_user_photo.png)
  final verify_user_photo = r'assets/images/profile/verify_user_photo.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/premium_image.png)
  final premium_image = r'assets/images/profile/premium_image.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/lines_bg.png)
  final lines_bg = r'assets/images/profile/lines_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/marker_icon.png)
  final marker_icon = r'assets/images/profile/marker_icon.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/anime_empty.png)
  final anime_empty = r'assets/images/profile/anime_empty.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/anime_header.png)
  final anime_header = r'assets/images/profile/anime_header.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/profile/spotify_bg.png)
  final spotify_bg = r'assets/images/profile/spotify_bg.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/match/match_successful.png)
  final match_successful = r'assets/images/match/match_successful.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/chat/empty_conversation_search.png)
  final empty_conversation_search = r'assets/images/chat/empty_conversation_search.png';

  /// ![](/Users/daniel/Desktop/work/senpai/assets/images/chat/empty_conversations.png)
  final empty_conversations = r'assets/images/chat/empty_conversations.png';
}

class _SvgResources {
  const _SvgResources();
}
